"""6. Auto creating table: votes

Revision ID: b4df3b1ff69d
Revises: 2a79a8a5b7dd
Create Date: 2022-04-20 20:09:15.904964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4df3b1ff69d'
down_revision = '2a79a8a5b7dd'
branch_labels = None
depends_on = None

"""
This was created by using the autogenerate command:
alembic revision --autogenerate -m "message for the revision"
"""


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('votes',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('post_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['post_id'], ['posts.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('user_id', 'post_id')
                    )
    op.add_column('posts', sa.Column('users_id', sa.Integer(), nullable=False))
    op.drop_constraint('post_users_fk', 'posts', type_='foreignkey')
    op.create_foreign_key("post_users_fk", 'posts', 'users', [
                          'users_id'], ['id'], ondelete='CASCADE')
    op.drop_column('posts', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_id', sa.INTEGER(),
                  autoincrement=False, nullable=False))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('post_users_fk', 'posts', 'users', [
                          'user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('posts', 'users_id')
    op.drop_table('votes')
    # ### end Alembic commands ###
