name: Build and Deploy

on: [push, pull_request]

jobs:
  setting_up:
    runs-on: ubuntu-latest
    steps:
      - name: Pull git repo
        uses: actions/checkout@v2
      - name: Install Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Installing requirements
        run: pip install -r requirements.txt